# Generated by Django 5.0.1 on 2024-01-19 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('google_api_place_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('rating', models.CharField(max_length=256)),
                ('open_now', models.CharField(max_length=256, null=True)),
                ('mobile_number', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=256)),
                ('photos', models.TextField(null=True)),
                ('reviews', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256, null=True)),
                ('verification_link', models.CharField(max_length=256, null=True)),
                ('email_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('bookmarked', models.BooleanField(default=False)),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karibunami.place')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karibunami.user')),
            ],
        ),
    ]
