# Generated by Django 5.0.1 on 2024-01-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karibunami', '0002_alter_bookmark_user_id_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='user_name',
            field=models.CharField(default='John Doe', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='user_id',
            field=models.CharField(max_length=256),
        ),
    ]
